### PR TITLE
OS X/Linux compatibility: use find_library()

### PR DESCRIPTION
**Pull request by est**
we don't have to hard code `libcrypto.so.1.0.0`.

### CODE REVIEW

**Comment by vbwagner** [comment]
Unfortunately, find_library doesn't work on relatively recent debian linux systems. Especially - on mulitarch ones.

**Comment by vbwagner** [comment]
Moreover,  there could be ABI changes when new version of OpenSSL comes out.

**Comment by vbwagner** [comment]
Ok, I've found out why your code is not working on my linux systems.
I've have to use

find_library('crypto') instead of find_library('libcrypto') to make it work.
Please check if this syntax work on your OS.
I'll also have to check whether it would work on Windows

**Comment by est** [comment]
I can confirm using `ctypes.util.find_library('crypto')` works on Mac OS X 10.10.3 Python 2.7.8.

For Windows I assume you have to either compile libeay or using Microsoft's `schannel`

**Comment by vbwagner** [comment]
So, I can write in wiki, that current state of module works in MacOS 10.10?

I've tested windows myself yesterday. It is quite easy to compile OpenSSL for Windows, if you have Linux development machine handy.

Using Windows Crypto API instead of OpenSSL is quite complicated thing. First of all there are different versions of it. See a [technet article](http://social.technet.microsoft.com/wiki/contents/articles/31296.implementing-sha-2-in-active-directory-certificate-services.aspx) Second, you have to deal with system certificate store, unexportable keys, accessable via handles only and lots of such security theater.

May be I do it sometime, but I doubt that it would be possible to maintain interface compatibility with ctypes crypto.

Really, under *Nix there are different crypto libraries to. There is Mozilla libnss, there is gcrypt and gnutls. Some software is able to be compiled with all of them (including microsoft CAPI on windows),. but it is quite hard job to maintain it.

**Comment by est** [comment]
> So, I can write in wiki, that current state of module works in MacOS 10.10?


Yes! 

About Windows, I vaguely remember that if you install CPython or ActivePython, there's libeay32.dll coming along because the standard library has a `ssl` module.

**Comment by vbwagner** [comment]
Not  every build  of python. Official 32-bit python 2.7.6 doesn't ship it. It has _hashlib.pyd and _ssl.pyd statically compiled. But 64-bit mercurial on my machine, which seems to be py2exe application, does ship it.

Really, main purpose of my work with ctypescrypto was ability to use loadable engines (because GOST cryptography is only provided by engines). So I need full installation of OpenSSL with configuration file, certificate store, engines etc, not just standalone libeay32.dll.

**Pull request closed without merging**
